version: '3'
services:
  oai-basestation:
    build: .
    volumes:
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    privileged: true
